USE [master]
GO
/****** Object:  Database [Agencia_de_viajes]    Script Date: 10/30/2025 8:00:49 PM ******/
CREATE DATABASE [Agencia_de_viajes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Agencia_de_viajes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Agencia_de_viajes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Agencia_de_viajes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Agencia_de_viajes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Agencia_de_viajes] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Agencia_de_viajes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Agencia_de_viajes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET ARITHABORT OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Agencia_de_viajes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Agencia_de_viajes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Agencia_de_viajes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Agencia_de_viajes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Agencia_de_viajes] SET  MULTI_USER 
GO
ALTER DATABASE [Agencia_de_viajes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Agencia_de_viajes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Agencia_de_viajes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Agencia_de_viajes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Agencia_de_viajes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Agencia_de_viajes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Agencia_de_viajes] SET QUERY_STORE = ON
GO
ALTER DATABASE [Agencia_de_viajes] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Agencia_de_viajes]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 10/30/2025 8:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[idCliente] [int] IDENTITY(1,1) NOT NULL,
	[dni] [varchar](12) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
	[apellido] [varchar](100) NOT NULL,
	[fechaNacimiento] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Compra]    Script Date: 10/30/2025 8:00:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Compra](
	[idCompra] [int] IDENTITY(1,1) NOT NULL,
	[idReserva] [int] NULL,
	[fecha] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idCompra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LineaDetalle]    Script Date: 10/30/2025 8:00:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LineaDetalle](
	[idLineaDetalle] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](1) NULL,
	[idReserva] [int] NULL,
	[idPaquete] [int] NULL,
	[precio] [smallmoney] NULL,
	[cantidad] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[idLineaDetalle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Paquete]    Script Date: 10/30/2025 8:00:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Paquete](
	[idPaquete] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](1) NULL,
	[precio] [smallmoney] NULL,
	[cupo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[idPaquete] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Paquete_Servicio]    Script Date: 10/30/2025 8:00:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Paquete_Servicio](
	[idPaqueteServicio] [int] IDENTITY(1,1) NOT NULL,
	[idServicio] [int] NULL,
	[idPaquete] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[idPaqueteServicio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Proveedor]    Script Date: 10/30/2025 8:00:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Proveedor](
	[idProveedor] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
	[email] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idProveedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reserva]    Script Date: 10/30/2025 8:00:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reserva](
	[idReserva] [int] IDENTITY(1,1) NOT NULL,
	[idCliente] [int] NULL,
	[fecha] [date] NOT NULL,
	[estado] [varchar](100) NOT NULL,
	[total] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idReserva] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Servicio]    Script Date: 10/30/2025 8:00:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Servicio](
	[idServicio] [int] IDENTITY(1,1) NOT NULL,
	[idProveedor] [int] NULL,
	[nombre] [varchar](1) NULL,
	[costo] [smallmoney] NULL,
	[precio] [smallmoney] NULL,
	[cupo] [int] NULL,
	[estado] [varchar](1) NULL,
	[descripcion] [varchar](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[idServicio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Compra]  WITH CHECK ADD FOREIGN KEY([idReserva])
REFERENCES [dbo].[Reserva] ([idReserva])
GO
ALTER TABLE [dbo].[LineaDetalle]  WITH CHECK ADD FOREIGN KEY([idPaquete])
REFERENCES [dbo].[Paquete] ([idPaquete])
GO
ALTER TABLE [dbo].[LineaDetalle]  WITH CHECK ADD FOREIGN KEY([idReserva])
REFERENCES [dbo].[Reserva] ([idReserva])
GO
ALTER TABLE [dbo].[Paquete_Servicio]  WITH CHECK ADD FOREIGN KEY([idPaquete])
REFERENCES [dbo].[Paquete] ([idPaquete])
GO
ALTER TABLE [dbo].[Paquete_Servicio]  WITH CHECK ADD FOREIGN KEY([idServicio])
REFERENCES [dbo].[Servicio] ([idServicio])
GO
ALTER TABLE [dbo].[Reserva]  WITH CHECK ADD FOREIGN KEY([idCliente])
REFERENCES [dbo].[Cliente] ([idCliente])
GO
ALTER TABLE [dbo].[Servicio]  WITH CHECK ADD FOREIGN KEY([idProveedor])
REFERENCES [dbo].[Proveedor] ([idProveedor])
GO
USE [master]
GO
ALTER DATABASE [Agencia_de_viajes] SET  READ_WRITE 
GO
